### ISSUE TITLE
redirect another page

### ISSUE THREAD

**Issue by MrMyatNoe** [nanyan-team/hallinto-nuxt#11]
How to redirect another page?f
I created new vue( usercreate.vue) and it shows me error in that template. and i call it that page instead of dashboard after login, it shows 404 error.

**Comment by wai-lin** [comment]
@MrMyatNoe , You need to tell me about your folder structure. I assume you are making new component instead of creating a new page, which is the wrong folder.

**Comment by MrMyatNoe** [comment]
This is folder structure.

![Screenshot from 2021-01-19 20-08-03](https://user-images.githubusercontent.com/33978217/105179796-228f5300-5b58-11eb-9381-0422f99639d7.png)

**Comment by MrMyatNoe** [comment]
I got the solution because of naming
